#!/bin/bash
BUILD_FOLDER=release
CPUCOUNT=`awk '/processor/{i++}END{print i}' /proc/cpuinfo`
[ ! -d $DEBUG_FOLDER ] && mkdir $DEBUG_FOLDER
pushd $DEBUG_FOLDER
cmake -DCMAKE_BUILD_TYPE=Release ..
make -j $CPUCOUNT
popd
